### ISSUE TITLE
Allow environment variable to set route prefix

### ISSUE THREAD

**Issue by Kampe** [simonwep/genesis#4]
currently default route for everything is / - this should be configurable, however something like /api/ would be ideal as default that's how Ocular frontend is configured.

**Comment by simonwep** [comment]
Under normal circumstances this shouldn't be required as you would usually run this behind a reverse-proxy. But I can see this making sense in some cases :)

**Comment by simonwep** [comment]
You can now do this via `GENESIS_BASE_URL` :)
